export const INIT_CATEGORY_DATA = 'INIT_CATEGORY_DATA';
export const SET_CATEGORY_DATA = 'SET_CATEGORY_DATA';
export const FETCH_CATEGORY_DATA_FAILED = 'FETCH_CATEGORY_DATA_FAILED';

export const INIT_SUB_CATEGORY_PAGE_DATA = 'INIT_SUB_CATEGORY_PAGE_DATA';
export const SET_SUB_CATEGORY_PAGE_DATA = 'SET_SUB_CATEGORY_PAGE_DATA';
export const FETCH_SUB_CATEGORY_PAGE_DATA_FAILED = 'FETCH_SUB_CATEGORY_PAGE_DATA_FAILED';