export const INIT_CATEGORY_DATA = 'INIT_CATEGORY_DATA';
export const SET_CATEGORY_DATA = 'SET_CATEGORY_DATA';
export const FETCH_CATEGORY_DATA_FAILED = 'FETCH_CATEGORY_DATA_FAILED';

export const INIT_SUB_CATEGORY_PAGE_DATA = 'INIT_SUB_CATEGORY_PAGE_DATA';
export const SET_SUB_CATEGORY_PAGE_DATA = 'SET_SUB_CATEGORY_PAGE_DATA';
export const FETCH_SUB_CATEGORY_PAGE_DATA_FAILED = 'FETCH_SUB_CATEGORY_PAGE_DATA_FAILED';

export const INIT_THREAD_DATA = 'INIT_THREAD_DATA';
export const SET_THREAD_DATA = 'SET_THREAD_DATA';
export const FETCH_THREAD_DATA_FAILED = 'FETCH_THREAD_DATA_FAILED';

export const INIT_CREATE_CATEGORY = 'INIT_CREATE_CATEGORY';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILED = 'CREATE_CATEGORY_FAILED';